package main

// FI source registry — v1 minimal: 4 verified OPUS sources for pilot.
// Sizes are point-in-time from the OPUS API research turn; the fetcher's
// own HEAD probe records actual byte counts at run time.
//
// Adding a new source: define it here with a verified URL + format.
// Folder-driven sources (epub, manual, fixture) are NOT in this registry —
// they're discovered by walking <lang>-corpus/*/manifest.json.
var sourcesFI = []Source{
	{
		Slug:     "opus-tatoeba",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-Tatoeba/v2023-04-12/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC BY 2.0 FR (Tatoeba)",
		Notes:    "Conversational sentences. ~10 MB. Pilot-ready.",
	},
	{
		Slug:     "opus-bible",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-bible-uedin/v1/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Public Domain / various (bible-uedin)",
		Notes:    "Religious text. ~15 MB.",
	},
	{
		Slug:     "opus-emea",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-EMEA/v3/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Public (EMEA)",
		Notes:    "European Medicines Agency leaflets. ~20 MB.",
	},
	{
		Slug:     "opus-ecb",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-ECB/v1/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Public (ECB)",
		Notes:    "European Central Bank documents. ~71 MB.",
	},
	{
		Slug:     "opus-europarl",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-Europarl/v8/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Public (Europarl)",
		Notes:    "European Parliament proceedings. ~97 MB.",
	},
	{
		Slug:     "opus-finlex",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-Finlex/v2018/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Public (Finlex; Finnish legal corpus)",
		Notes:    "Finnish legal documents. ~97 MB.",
	},
	{
		Slug:     "opus-eubookshop",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-EUbookshop/v2/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Public (EU Bookshop)",
		Notes:    "EU publications. ~132 MB.",
	},
	{
		Slug:     "opus-wikimatrix",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-WikiMatrix/v1/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC BY-SA (Wikipedia derivative)",
		Notes:    "Wikipedia parallel sentences. ~213 MB.",
	},
	{
		Slug:     "opus-jrc-acquis",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-JRC-Acquis/v3.0/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Public (JRC-Acquis)",
		Notes:    "EU legal corpus. ~80 MB.",
	},
	{
		Slug:     "opus-opensubtitles",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-OpenSubtitles/v2024/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "OpenSubtitles ToS (local-only)",
		Notes:    "Movie/TV subtitles, conversational. ~1.07 GB. Big — fetch deliberately.",
	},
	{
		Slug:     "opus-ted2020",
		Lang:     "fi",
		Kind:     "prose",
		Format:   "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-TED2020/v1/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC BY-NC-ND (TED talks)",
		Notes:    "TED talks transcripts. ~25 MB.",
	},
	// === Heavy OPUS (~10 GB combined) ===
	{
		Slug: "opus-hplt", Lang: "fi", Kind: "prose", Format: "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-HPLT/v3/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC0 (HPLT)",
		Notes:    "HPLT v3 web crawl, ~2.35 GB",
	},
	{
		Slug: "opus-ccmatrix", Lang: "fi", Kind: "prose", Format: "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-CCMatrix/v1/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "Open (CCMatrix)",
		Notes:    "CCMatrix mined parallel sentences, ~2.21 GB",
	},
	{
		Slug: "opus-nllb", Lang: "fi", Kind: "prose", Format: "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-NLLB/v1/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC BY-NC (NLLB)",
		Notes:    "Meta NLLB mined sentences, ~2.20 GB",
	},
	{
		Slug: "opus-multihplt", Lang: "fi", Kind: "prose", Format: "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-MultiHPLT/v3/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC0 (HPLT)",
		Notes:    "MultiHPLT v3, ~1.87 GB",
	},
	{
		Slug: "opus-paracrawl", Lang: "fi", Kind: "prose", Format: "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-ParaCrawl/v9/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC0 (ParaCrawl)",
		Notes:    "Web crawl, ~1.29 GB",
	},
	{
		Slug: "opus-multiparacrawl", Lang: "fi", Kind: "prose", Format: "gz",
		URL:      "https://object.pouta.csc.fi/OPUS-MultiParaCrawl/v9b/mono/fi.txt.gz",
		Filename: "fi.txt.gz",
		License:  "CC0 (ParaCrawl)",
		Notes:    "MultiParaCrawl v9b, ~955 MB",
	},
	// === Yle Kielipankki (public scrambled VRT) ===
	{
		Slug: "yle-news-2022-2024", Lang: "fi", Kind: "prose", Format: "vrt_zip",
		URL:      "https://www.kielipankki.fi/download/YLE/fi/2022-2024-s-vrt/ylenews-fi-2022-2024-s-vrt.zip",
		Filename: "ylenews-fi-2022-2024-s-vrt.zip",
		License:  "Yle Areena terms (local-only)",
		Notes:    "Yle News 2022-2024 scrambled VRT (no login required), ~892 MB",
	},
	{
		Slug: "yle-news-2011-2018", Lang: "fi", Kind: "prose", Format: "vrt_zip",
		URL:      "https://www.kielipankki.fi/download/YLE/fi/2011-2018-s-vrt/ylenews-fi-2011-2018-s-vrt.zip",
		Filename: "ylenews-fi-2011-2018-s-vrt.zip",
		License:  "Yle Areena terms (local-only)",
		Notes:    "Yle News 2011-2018 scrambled VRT, ~2.81 GB",
	},
	// === Wikipedia FI XML dump ===
	{
		Slug: "wikipedia-fi", Lang: "fi", Kind: "prose", Format: "wikipedia_dump",
		URL:      "https://dumps.wikimedia.org/fiwiki/latest/fiwiki-latest-pages-articles.xml.bz2",
		Filename: "fiwiki-latest-pages-articles.xml.bz2",
		License:  "CC BY-SA 4.0 (Wikipedia)",
		Notes:    "Finnish Wikipedia full dump, ~968 MB bz2",
	},
	// === Leipzig Corpora FI ===
	{
		Slug: "leipzig-fi-news-2020", Lang: "fi", Kind: "prose", Format: "leipzig",
		URL:      "https://downloads.wortschatz-leipzig.de/corpora/fin_news_2020_1M.tar.gz",
		Filename: "fin_news_2020_1M.tar.gz",
		License:  "CC BY (Leipzig Corpora)",
		Notes:    "Leipzig FI news 2020, 1M sentences, ~161 MB",
	},
	{
		Slug: "leipzig-fi-newscrawl-2017", Lang: "fi", Kind: "prose", Format: "leipzig",
		URL:      "https://downloads.wortschatz-leipzig.de/corpora/fin_newscrawl_2017_1M.tar.gz",
		Filename: "fin_newscrawl_2017_1M.tar.gz",
		License:  "CC BY (Leipzig Corpora)",
		Notes:    "Leipzig FI newscrawl 2017, 1M sentences, ~172 MB",
	},
	{
		Slug: "leipzig-fi-wikipedia-2021", Lang: "fi", Kind: "prose", Format: "leipzig",
		URL:      "https://downloads.wortschatz-leipzig.de/corpora/fin_wikipedia_2021_1M.tar.gz",
		Filename: "fin_wikipedia_2021_1M.tar.gz",
		License:  "CC BY-SA (Wikipedia derivative)",
		Notes:    "Leipzig FI Wikipedia 2021, 1M sentences, ~168 MB",
	},
	// === FrequencyWords ===
	{
		Slug: "frequency-words-fi", Lang: "fi", Kind: "prose", Format: "text",
		URL:      "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/fi/fi_50k.txt",
		Filename: "fi_50k.txt",
		License:  "CC BY-SA 4.0 (Hermit Dave OpenSubtitles 2018)",
		Notes:    "Top-50k FI surface forms, OpenSubtitles 2018-derived",
	},
}
