package textfilter

import (
	"strings"
	"testing"
)

func TestShouldSkipEPUBResource(t *testing.T) {
	tests := []struct {
		name string
		raw  string
		want bool
	}{
		{name: "OEBPS/nav.xhtml", want: true},
		{name: "OPS/Text/toc01.xhtml", want: true},
		{name: "OPS/frontmatter/titlepage.xhtml", want: true},
		{name: "OPS/Text/sisukord.xhtml", want: true},
		{name: "OPS/Text/chapter-01.xhtml", want: false},
		{name: "OPS/Text/part0001.xhtml", raw: `<html><body><nav epub:type="toc"><ol><li>Chapter</li></ol></nav></body></html>`, want: true},
	}
	for _, tt := range tests {
		if got := ShouldSkipEPUBResource(tt.name, []byte(tt.raw)); got != tt.want {
			t.Fatalf("ShouldSkipEPUBResource(%q) = %v, want %v", tt.name, got, tt.want)
		}
	}
}

func TestCleanEPUBTextDropsResidueLines(t *testing.T) {
	in := strings.Join([]string{
		"Sisällys",
		"Sisukord",
		"",
		"Luku 1",
		"Peatükk 2",
		"",
		"Tämä on oikea esimerkkilause.",
		"ISBN 978-1-234-56789-0",
		"Kõik õigused kaitstud",
		"Kiitos.",
	}, "\n")
	got := CleanEPUBText(in)
	if strings.Contains(got, "Sisällys") || strings.Contains(got, "Sisukord") ||
		strings.Contains(got, "Luku 1") || strings.Contains(got, "Peatükk") ||
		strings.Contains(got, "ISBN") || strings.Contains(got, "Kõik õigused") {
		t.Fatalf("CleanEPUBText kept residue:\n%s", got)
	}
	if !strings.Contains(got, "Tämä on oikea esimerkkilause.") || !strings.Contains(got, "Kiitos.") {
		t.Fatalf("CleanEPUBText dropped valid prose:\n%s", got)
	}
}

func TestIsUserFriendlySentence(t *testing.T) {
	tests := []struct {
		text string
		want bool
	}{
		{text: "Tämä on hyvä esimerkkilause.", want: true},
		{text: "See on hea eestikeelne näitelause.", want: true},
		{text: "Kiitos.", want: true},
		{text: "Tule heti tänne", want: true},
		{text: "He won the copyright case.", want: true},
		{text: "This calibre was rare.", want: true},
		{text: "The cover design made everyone talk.", want: true},
		{text: "ISBN 978-1-234-56789-0", want: false},
		{text: "Copyright 2024 Kirjastus", want: false},
		{text: "Generated by calibre 5.0", want: false},
		{text: "Cover design: John Doe", want: false},
		{text: "J. R. R. Tolkien", want: false},
		{text: "Harry Potter ja Azkabanin vanki", want: false},
		{text: "Luku 12", want: false},
		{text: "Peatükk 12", want: false},
		{text: "Eessõna", want: false},
		{text: "Sisällys", want: false},
		{text: "Sisukord", want: false},
		{text: "Tõlkinud Mari Mets", want: false},
		{text: "Kirjastus Eesti Raamat", want: false},
		{text: "https://example.test", want: false},
	}
	for _, tt := range tests {
		if got := IsUserFriendlySentence(tt.text); got != tt.want {
			t.Fatalf("IsUserFriendlySentence(%q) = %v, want %v", tt.text, got, tt.want)
		}
	}
}
